# Generated by Django 3.2.13 on 2022-06-03 08:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('simpleapp', '0006_auto_20220603_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='author_to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.user'),
        ),
    ]
